// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-todos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}

// src/lib/mcp/tools/list-todos.ts
var list_todos_default = defineTool({
  name: "list_todos",
  title: "List to-dos",
  description: "List the signed-in user's to-do items, optionally filtered by completion status.",
  inputSchema: {
    done: z.boolean().optional().describe("If set, only return todos with this completion status."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ done, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    let q = supabaseForUser(ctx).from("todos").select("id,title,due_at,done,created_at,position").order("position", { ascending: true }).limit(limit ?? 50);
    if (typeof done === "boolean") q = q.eq("done", done);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { todos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-todo.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var create_todo_default = defineTool2({
  name: "create_todo",
  title: "Create to-do",
  description: "Create a to-do item for the signed-in user. Optionally schedule a due date/time (ISO 8601).",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Task text."),
    due_at: z2.string().datetime().optional().describe("Due date/time as ISO 8601, e.g. 2026-07-20T14:00:00Z.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, due_at }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const sb = supabaseForUser(ctx);
    const { data: maxRow } = await sb.from("todos").select("position").order("position", { ascending: false }).limit(1).maybeSingle();
    const nextPos = (maxRow?.position ?? 0) + 1;
    const { data, error } = await sb.from("todos").insert({ user_id: ctx.getUserId(), title, due_at: due_at ?? null, position: nextPos }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created todo: ${data.title}` }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/complete-todo.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var complete_todo_default = defineTool3({
  name: "complete_todo",
  title: "Complete or reopen to-do",
  description: "Mark a to-do as done or not done.",
  inputSchema: {
    id: z3.string().uuid().describe("Todo id."),
    done: z3.boolean().describe("true = mark done, false = reopen.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, done }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("todos").update({ done }).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: done ? "Marked done" : "Reopened" }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/search-customers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var search_customers_default = defineTool4({
  name: "search_customers",
  title: "Search customers",
  description: "Search the customer notebook by name, phone, email, designer, or 'looking for' tags. Returns up to 50 matches.",
  inputSchema: {
    query: z4.string().trim().min(1).optional().describe("Text to match. Omit to list recent customers."),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    let q = supabaseForUser(ctx).from("customers").select("id,name,phone,email,designers,looking_for,shoe_size,width,typed_notes,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (query) {
      const like = `%${query}%`;
      q = q.or(
        `name.ilike.${like},phone.ilike.${like},email.ilike.${like},typed_notes.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const filtered = query ? (data ?? []).filter((c) => {
      const hay = [
        c.name,
        c.phone,
        c.email,
        c.typed_notes,
        ...c.designers ?? [],
        ...c.looking_for ?? []
      ].filter(Boolean).join(" ").toLowerCase();
      return hay.includes(query.toLowerCase());
    }) : data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(filtered) }],
      structuredContent: { customers: filtered }
    };
  }
});

// src/lib/mcp/tools/get-customer.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var get_customer_default = defineTool5({
  name: "get_customer",
  title: "Get customer",
  description: "Fetch full details for one customer, including typed notes and custom fields.",
  inputSchema: { id: z5.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("customers").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Customer not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { customer: data }
    };
  }
});

// src/lib/mcp/tools/create-customer.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var create_customer_default = defineTool6({
  name: "create_customer",
  title: "Create customer",
  description: "Add a new customer to the notebook.",
  inputSchema: {
    name: z6.string().trim().min(1),
    phone: z6.string().trim().optional(),
    email: z6.string().trim().email().optional(),
    designers: z6.array(z6.string()).optional().describe("Preferred designers, e.g. ['Manolo','Aquazzura']."),
    shoe_size: z6.number().optional(),
    width: z6.enum(["Narrow", "Medium", "Wide"]).optional(),
    looking_for: z6.array(z6.string()).optional(),
    typed_notes: z6.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("customers").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      phone: input.phone ?? null,
      email: input.email ?? null,
      designers: input.designers ?? [],
      looking_for: input.looking_for ?? [],
      shoe_size: input.shoe_size ?? null,
      width: input.width ?? null,
      typed_notes: input.typed_notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created customer: ${data.name}` }],
      structuredContent: { customer: data }
    };
  }
});

// src/lib/mcp/tools/append-customer-note.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^4.4.3";
var append_customer_note_default = defineTool7({
  name: "append_customer_note",
  title: "Append customer note",
  description: "Append a line to a customer's typed notes (adds a timestamp prefix).",
  inputSchema: {
    id: z7.string().uuid(),
    note: z7.string().trim().min(1)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, note }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const sb = supabaseForUser(ctx);
    const { data: cur, error: readErr } = await sb.from("customers").select("typed_notes").eq("id", id).maybeSingle();
    if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
    if (!cur) return { content: [{ type: "text", text: "Customer not found" }], isError: true };
    const stamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const next = [cur.typed_notes, `[${stamp}] ${note}`].filter(Boolean).join("\n");
    const { data, error } = await sb.from("customers").update({ typed_notes: next }).eq("id", id).select("id,typed_notes").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Note appended." }],
      structuredContent: { customer: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bsraswwvdukplopxadmw";
var mcp_default = defineMcp({
  name: "atelier-mcp",
  title: "Atelier \u2014 Notebook & To-Do",
  version: "0.1.0",
  instructions: "Tools for the Atelier app: manage the signed-in user's to-do list and their private women's-footwear customer notebook (search customers, read details, create customers, append notes).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_todos_default,
    create_todo_default,
    complete_todo_default,
    search_customers_default,
    get_customer_default,
    create_customer_default,
    append_customer_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
